spring.application.name=ecommerce-fraud-risk-platform
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fraudrisk}
spring.datasource.username=${DB_USERNAME:frauduser}
spring.datasource.password=${DB_PASSWORD:fraudpass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

risk.engine.python=${PYTHON_EXECUTABLE:python3}
risk.engine.script=${RISK_ENGINE_SCRIPT:scripts/risk_engine.py}
